// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoVXkUfcu6rVMGCmqdvxQlFGpiefFkAM',
    appId: '1:716716986361:web:8b0fbb8b6b87a46da63728',
    messagingSenderId: '716716986361',
    projectId: 'test-73cb3',
    authDomain: 'test-73cb3.firebaseapp.com',
    storageBucket: 'test-73cb3.firebasestorage.app',
    measurementId: 'G-BJSW43MG2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACC819bNHbyYAGUPeE4p3vBI3uK1kK2Vk',
    appId: '1:716716986361:android:dc71a2cc55d0a499a63728',
    messagingSenderId: '716716986361',
    projectId: 'test-73cb3',
    storageBucket: 'test-73cb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhKVVC4IkUmrJJjKyPFVJds3Ys845OPo',
    appId: '1:716716986361:ios:6ee6ae24331c4f16a63728',
    messagingSenderId: '716716986361',
    projectId: 'test-73cb3',
    storageBucket: 'test-73cb3.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYhKVVC4IkUmrJJjKyPFVJds3Ys845OPo',
    appId: '1:716716986361:ios:6ee6ae24331c4f16a63728',
    messagingSenderId: '716716986361',
    projectId: 'test-73cb3',
    storageBucket: 'test-73cb3.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnoVXkUfcu6rVMGCmqdvxQlFGpiefFkAM',
    appId: '1:716716986361:web:764a6a0e1d7a8e84a63728',
    messagingSenderId: '716716986361',
    projectId: 'test-73cb3',
    authDomain: 'test-73cb3.firebaseapp.com',
    storageBucket: 'test-73cb3.firebasestorage.app',
    measurementId: 'G-9SC46EFF54',
  );

}